#!/bin/bash

clear
echo -e "================================================="
echo -e "#         Premium Auto Script By AditGabrok404       #"
echo -e "#-----------------------------------------------#"
echo -e "# For Debian 9 & Debian 10 64 bit               #"
echo -e "# For Ubuntu 18.04 & Ubuntu 20.04 64 bit        #"
echo -e "# For VPS with KVM and VMWare virtualization    #"
echo -e "# Build Up By ADITGABROK404                           #"
echo -e "#-----------------------------------------------#"
echo -e "# Thanks To                                     #"
echo -e "#-----------------------------------------------#"
echo -e "# ALLAH S.W.T                                  #"
echo -e "# My Family                                     #"
echo -e "# Google                                        #"
echo -e "# YouTube                                        #"
echo -e "# Admin Portal & White Vps                      #"
echo -e "# Jhon Arjuna 1335                      #"
echo -e "# Faisal                      #"
echo -e "# Sanzking                      #"
echo -e "# Dimas Dm                      #"
echo -e "# Kewek                      #"
echo -e "#                                               #"
echo -e "#-----------------------------------------------#"
echo -e "================================================="
